// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ToxicDetectionBot.WebApi.Data;

#nullable disable

namespace ToxicDetectionBot.WebApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260103060528_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.1");

            modelBuilder.Entity("ToxicDetectionBot.WebApi.Data.UserAlignmentScore", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<int>("ChaoticEvilCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ChaoticGoodCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ChaoticNeutralCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DominantAlignment")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("LawfulEvilCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LawfulGoodCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LawfulNeutralCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NeutralEvilCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NeutralGoodCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("SummarizedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("TrueNeutralCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("UserId");

                    b.ToTable("UserAlignmentScores");
                });

            modelBuilder.Entity("ToxicDetectionBot.WebApi.Data.UserOptOut", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsOptedOut")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastChangedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId");

                    b.HasIndex("IsOptedOut");

                    b.ToTable("UserOptOuts");
                });

            modelBuilder.Entity("ToxicDetectionBot.WebApi.Data.UserSentiment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Alignment")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ChannelName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("GuildId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("GuildName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsSummarized")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsToxic")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MessageContent")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MessageId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ChannelName");

                    b.HasIndex("GuildId");

                    b.HasIndex("GuildName");

                    b.HasIndex("IsSummarized");

                    b.HasIndex("UserId");

                    b.ToTable("UserSentiments");
                });

            modelBuilder.Entity("ToxicDetectionBot.WebApi.Data.UserSentimentScore", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<int>("NonToxicMessages")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("SummarizedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalMessages")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ToxicMessages")
                        .HasColumnType("INTEGER");

                    b.Property<double>("ToxicityPercentage")
                        .HasColumnType("REAL");

                    b.HasKey("UserId");

                    b.ToTable("UserSentimentScores");
                });
#pragma warning restore 612, 618
        }
    }
}
